name: checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - uses: ./.github/actions/prepare

      - name: Check Types
        run: bun check:types

  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - uses: ./.github/actions/prepare

      - name: Check JS Codestyle
        run: bun check:codestyle

  checks-passed:
    if: always()
    name: checks:required
    needs: [types, codestyle]
    runs-on: ubuntu-latest
    steps:
      - name: Check all jobs passed
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "Some jobs failed or were cancelled"
            exit 1
          fi
          echo "All CI jobs passed"
